### ISSUE TITLE
JpaFhirTerminologyProvider should return false if Code null

### ISSUE THREAD

**Issue by nkarip** [DBCG/cql_engine#15]
JpaFhirTerminologyProvider "in" function throws null pointer exception if Code parameter is null. Should return false. Otherwise InValueSet expression where left hand operand evaluates to null throws exception.

**Comment by c-schuler** [comment]
Please provide an example of when this is failing.
I have run the following test case, which doesn't throw an exception and results in Null as expected:
`null as Code in "Test valueset"`

**Comment by nkarip** [comment]
I'm actually using ELM XML. Example below. If the property evaluates to null, then the left hand operand is a Concept object with a single null code entry in getCodes(). This causes an error at line 32 of JpaFhirTerminologyProvider. 

<operand xsi:type="InValueSet">
  <code xsi:type="ToConcept">
    <operand path="vaccineCode.coding" scope="Immun" xsi:type="Property"/>
  </code>
  <valueset name="Fluvax" xsi:type="ValueSetRef"/>
</operand>

**Comment by c-schuler** [comment]
Gotcha.
Fix is committed here: 80bf57e48a683101fc40e9be79c4dacffd03c181
This has been published to 1.2.2-SNAPSHOT (https://oss.sonatype.org/content/repositories/snapshots/org/opencds/cqf/) of the engine.

**Comment by nkarip** [comment]
Quick note on the fix to InValueSet evaluator - looks like line 78 was added to return null if Code object in Concept getCodes() is null. However, getCodes returns an array of Code objects, and I think if any one Code is null then it should still continue to evaluate the remaining Code objects in the array rather than returning null for the "in" result.

**Comment by brynrhodes** [comment]
Except that for the "in" operator, the specification says "if the left argument is null, the result is null", and the definition of a "Concept" is that every code in the concept is equivalent, so I think the interpretation of a "Concept" with a null code is that it is "null", so the result of asking if a "null" concept is in a value set is "null".
